file_format: "1"
id: temper_dongle
name: Chocofi Temper
type: shield
url: https://github.com/raeedcho/chocofi-temper
requires: [pro_micro]
features:
  - keys
siblings:
  - temper_dongle_left
  - temper_dongle_right
  - temper_dongle_dongle
